--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: imgclass
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: imageclassifier
  template: 
    metadata: 
      labels: 
        app: imageclassifier
    spec: 
      containers: 
        - 
          image: "gcr.io/dynamic-music-322221/myapp:v1"
          name: cv-app
          ports: 
            - 
              containerPort: 8501